name: Java CI

on: [push]
# on:
#   push:
#     branches:
#       - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: your_db_user
          POSTGRES_PASSWORD: your_db_password
          POSTGRES_DB: your_db_name
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5



    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      # - name: Build with Gradle
      #   run: ./gradlew build
      # - name: Run Application
      #   run: java -jar build/libs/your-application.jar
      - name: Test with Maven
        run: mvn --batch-mode --update-snapshots package
